import { OnInit, EventEmitter, DoCheck, IterableDiffers, QueryList, OnDestroy } from '@angular/core';
import { ThyGridColumn, ThyMultiSelectEvent, ThyRadioSelectEvent, ThyPage, ThyGridEmptyOptions, ThySwitchEvent, ThyGridDraggableEvent, ThyGridRowEvent, ThyGridEvent } from './grid.interface';
import { PageChangedEvent } from 'ngx-bootstrap/pagination';
import { ThyGridColumnComponent, IThyGridColumnParentComponent } from './grid-column.component';
import { SortablejsOptions } from 'angular-sortablejs';
export declare type ThyGridTheme = 'default' | 'bordered';
export declare class ThyGridComponent implements OnInit, OnDestroy, DoCheck, IThyGridColumnParentComponent {
    private _differs;
    customType: {
        index: string;
        checkbox: string;
        radio: string;
        switch: string;
    };
    model: object[];
    rowKey: string;
    columns: ThyGridColumn[];
    themeClass: string;
    className: string;
    rowClassName: string | Function;
    loadingDone: boolean;
    loadingText: string;
    emptyOptions: ThyGridEmptyOptions;
    draggable: boolean;
    draggableOptions: SortablejsOptions;
    selectedRadioRow: any;
    pagination: ThyPage;
    trackByFn: any;
    wholeRowSelect: boolean;
    private _filter;
    private _diff;
    private _draggableModel;
    private _listOfColumnComponents;
    thyModel: any;
    thyRowKey: any;
    thyTheme: ThyGridTheme;
    thyClassName: string;
    thyRowClassName: string | Function;
    thyLoadingDone: boolean;
    thyLoadingText: string;
    thyEmptyOptions: ThyGridEmptyOptions;
    thyDraggable: boolean | any;
    thyFilter: any;
    thyPageIndex: number;
    thyPageSize: number;
    thyPageTotal: number;
    thyWholeRowSelect: boolean;
    thyOnSwitchChange: EventEmitter<ThySwitchEvent>;
    thyOnPageChange: EventEmitter<PageChangedEvent>;
    thyOnMultiSelectChange: EventEmitter<ThyMultiSelectEvent>;
    thyOnRadioSelectChange: EventEmitter<ThyRadioSelectEvent>;
    thyOnDraggableChange: EventEmitter<ThyGridDraggableEvent>;
    thyOnRowClick: EventEmitter<ThyGridRowEvent>;
    thyOnRowContextMenu: EventEmitter<ThyGridEvent>;
    listOfColumnComponents: QueryList<ThyGridColumnComponent>;
    constructor(_differs: IterableDiffers);
    private _getSelectionKeys;
    private _initializeColumns;
    private _initializeDataModel;
    private _initialSelections;
    private _initialCustomModelValue;
    private _refreshCustomModelValue;
    private _applyDiffChanges;
    private _bindTrackFn;
    private _destroyInvalidAttribute;
    private _filterModel;
    updateColumnSelections(key: string, selections: any): void;
    isTemplateRef(ref: any): boolean;
    getModelValue(row: any, path: string): any;
    renderRowClassName(row: any, index: number): any;
    onModelChange(row: any, column: ThyGridColumn): void;
    onStopPropagation(event: Event): void;
    onPageChange(event: PageChangedEvent): void;
    onCheckboxChange(row: any, column: ThyGridColumn): void;
    onMultiSelectChange(event: Event, row: any, column: ThyGridColumn): void;
    onRadioSelectChange(event: Event, row: any): void;
    onSwitchChange(event: Event, row: any, column: any): void;
    onDraggableStart(event: any): void;
    onDraggableUpdate(event: any): void;
    onRowClick(event: Event, row: any): void;
    onRowContextMenu(event: Event, row: any): void;
    draggableStopPropagation(event: Event): void;
    ngOnInit(): void;
    ngDoCheck(): void;
    ngOnDestroy(): void;
}
