export declare function inputValueToBoolean(value: boolean | string): boolean;
export declare function isUndefined(value: any): boolean;
export declare function isNull(value: any): boolean;
export declare function isUndefinedOrNull(value: any): boolean;
export declare function isArray(value: any): boolean;
export declare function isEmpty(value: any): boolean;
export declare function isString(value: any): boolean;
export declare function isNumber(value: any): boolean;
export declare function isObject(value: any): boolean;
export declare function isFunction(value: any): boolean;
export declare function isDate(value: any): boolean;
export declare function coerceArray<T>(value: T | T[]): T[];
export declare function get(object: any, path: string, defaultValue?: any): any;
export declare function set(object: any, path: string, value: any): any;
export declare function isBoolean(value: any): boolean;
export declare function fromArray(value: any): any[];
export declare function htmlElementIsEmpty(element: HTMLElement): boolean;
export declare function hexToRgb(hexValue: any, alpha: number): string;
export declare function formatDate(date: Date | number): number;
