import { ElementRef, Renderer2, OnInit, EventEmitter, OnDestroy } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { ThyEditorService, ThyEditorConfig } from './editor.service';
import { ThyEditorLinkModuleService } from './editor-linkmodule.service';
export declare class ThyEditorComponent implements OnInit, ControlValueAccessor, OnDestroy {
    private elementRef;
    private renderer;
    thyEditorService: ThyEditorService;
    thyEditorLinkModuleService: ThyEditorLinkModuleService;
    model: any;
    options: ThyEditorConfig;
    config: ThyEditorConfig;
    editorWrap: ElementRef;
    placeholder: string;
    className: String;
    _thyWrapperClass: boolean;
    _thyFullClass: boolean;
    uploadImg: EventEmitter<any>;
    value: String;
    constructor(elementRef: ElementRef, renderer: Renderer2, thyEditorService: ThyEditorService, thyEditorLinkModuleService: ThyEditorLinkModuleService);
    paste(e: any): void;
    mouseenter(e: any): void;
    mouseleave(e: any): void;
    hasParent(el: any, parent: any): boolean;
    writeValue(value: any): void;
    registerOnChange(fn: Function): void;
    registerOnTouched(fn: Function): void;
    onModelChange: Function;
    onModelTouched: Function;
    changeValue(event: Event): void;
    insertTable(): void;
    setHeaderLi(id: string): void;
    styleFn(name: string, event: Event): void;
    togglePreview(): void;
    selectFiles(event: Event): void;
    uploadImgAction(src: string, title: string): void;
    selectModule(event: Event): void;
    linkModuleAction(str: string): void;
    blurEditor(): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
}
